/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotarjetas;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class VentanaBanco extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBanco
     */
    private Banco banco;

    public VentanaBanco() {
        initComponents();
        banco = new Banco();
        cargarCombo(cboBoxTipoTarjeta);
        cargarCombo(cboBoxTipoTarjetaOperacion);
        cboBoxTipoTarjeta.setSelectedIndex(-1);
        cboBoxTipoTarjeta.setSelectedIndex(-1);

    }

    public void cargarCombo(JComboBox combo) {

//        combo = new JComboBox();
        combo.removeAllItems();//borra los items cargados en el combo por defecto        
        combo.addItem("Tarjeta de Debito");
        combo.addItem("Tarjeta de Credito");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        cboBoxTipoTarjeta = new javax.swing.JComboBox<>();
        lblTipoTarjeta = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        lblSaldo = new javax.swing.JLabel();
        txtTitular = new javax.swing.JTextField();
        lblTitular = new javax.swing.JLabel();
        txtLimite = new javax.swing.JTextField();
        lblLimite = new javax.swing.JLabel();
        btnAgregarTarjeta = new javax.swing.JButton();
        lblPromedioSaldosTarjetasCredito = new javax.swing.JLabel();
        lblSaldototalTarjetasDebito = new javax.swing.JLabel();
        btnMostrarReportes = new javax.swing.JButton();
        rbtExtraer = new javax.swing.JRadioButton();
        rbtDepositar = new javax.swing.JRadioButton();
        cboBoxTipoTarjetaOperacion = new javax.swing.JComboBox<>();
        lblTipoTarjetaOperacion = new javax.swing.JLabel();
        lblNumeroTarjetaOperar = new javax.swing.JLabel();
        txtNumeroTarjetaOperar = new javax.swing.JTextField();
        lblImporte = new javax.swing.JLabel();
        txtImporteOperar = new javax.swing.JTextField();
        btnOperar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNumero.setText("Numero: ");

        cboBoxTipoTarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTipoTarjeta.setText("Tipo Tarjeta:");

        lblSaldo.setText("Saldo:");

        lblTitular.setText("Titular:");

        lblLimite.setText("Limite: ");

        btnAgregarTarjeta.setText("Agregar");
        btnAgregarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTarjetaActionPerformed(evt);
            }
        });

        lblPromedioSaldosTarjetasCredito.setText("El Promedio de Saldo de Tarjetas de credito es de: ");

        lblSaldototalTarjetasDebito.setText("El Saldo Total de Tarjetas de Debitos es de: ");

        btnMostrarReportes.setText("Mostrar Reportes");
        btnMostrarReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarReportesActionPerformed(evt);
            }
        });

        grupoBotones.add(rbtExtraer);
        rbtExtraer.setText("Extraccion");
        rbtExtraer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtExtraerActionPerformed(evt);
            }
        });

        grupoBotones.add(rbtDepositar);
        rbtDepositar.setText("Deposito");

        cboBoxTipoTarjetaOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTipoTarjetaOperacion.setText("Tipo Tarjeta:");

        lblNumeroTarjetaOperar.setText("Numero Tarjeta ");

        lblImporte.setText("Importe");

        btnOperar.setText("Operar");
        btnOperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTipoTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboBoxTipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(txtSaldo)
                            .addComponent(txtTitular))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSaldototalTarjetasDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPromedioSaldosTarjetasCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblTipoTarjetaOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rbtExtraer, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNumeroTarjetaOperar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOperar)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNumeroTarjetaOperar)
                                        .addComponent(rbtDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboBoxTipoTarjetaOperacion, 0, 182, Short.MAX_VALUE)
                                        .addComponent(txtImporteOperar, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(65, 65, 65))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMostrarReportes)
                        .addGap(147, 147, 147))))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btnAgregarTarjeta)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboBoxTipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoTarjeta))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSaldototalTarjetasDebito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero)
                    .addComponent(lblPromedioSaldosTarjetasCredito))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldo)
                    .addComponent(btnMostrarReportes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitular))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLimite)
                    .addComponent(rbtExtraer)
                    .addComponent(rbtDepositar))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarTarjeta)
                    .addComponent(cboBoxTipoTarjetaOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoTarjetaOperacion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroTarjetaOperar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroTarjetaOperar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImporteOperar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImporte))
                .addGap(37, 37, 37)
                .addComponent(btnOperar)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtExtraerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtExtraerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtExtraerActionPerformed

    private void btnAgregarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTarjetaActionPerformed
        // TODO add your handling code here:
        int numeroTarjeta = Integer.parseInt(txtNumero.getText());
        float saldo = Float.parseFloat(txtSaldo.getText());
        String titular = txtTitular.getText();

        if (cboBoxTipoTarjeta.getSelectedIndex() == 0) { //TARJETA DE DEBITO
            Debito nuevaTarjeta = new Debito(numeroTarjeta, saldo, titular);
            banco.agregarTarjeta(nuevaTarjeta);
        } else if (cboBoxTipoTarjeta.getSelectedIndex() == 1) {//TARJETA DE CREDITO
            float limite = Float.parseFloat(txtLimite.getText());
            Credito nuevaTarCredito = new Credito(limite, numeroTarjeta, saldo, titular);
            banco.agregarTarjeta(nuevaTarCredito);
        }
    }//GEN-LAST:event_btnAgregarTarjetaActionPerformed

    private void btnMostrarReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarReportesActionPerformed
        // TODO add your handling code here:
//        float SaldoTotal=banco.saldoTotalTarjetaDebito();
        lblSaldototalTarjetasDebito.setText("El Saldo Total de Tarjetas de Debito es de: $" + banco.saldoTotalTarjetaDebito());
        lblPromedioSaldosTarjetasCredito.setText("El Promedio Total de Saldos de Tarjetas de Credito es de: $" + banco.promedioTotalTarjetaCredito());
    }//GEN-LAST:event_btnMostrarReportesActionPerformed

    private void btnOperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperarActionPerformed
        // TODO add your handling code here:
        int tipoTarjeta = cboBoxTipoTarjetaOperacion.getSelectedIndex();
        int nroTarjeta = Integer.parseInt(txtNumeroTarjetaOperar.getText());
        float importe = Float.parseFloat(txtImporteOperar.getText());

        if (rbtExtraer.isSelected()) {

            banco.extraer(nroTarjeta, tipoTarjeta, importe);
            if (banco.extraer(nroTarjeta, tipoTarjeta, importe) == true) {
                JOptionPane.showMessageDialog(this, "Operacion Exitosa");
            } else {
                JOptionPane.showMessageDialog(this, "La Operacion Fracasó");
            }
        }
        
        else if (rbtDepositar.isSelected()) {
            banco.depositar(nroTarjeta, tipoTarjeta, importe);
            if (banco.depositar(nroTarjeta, tipoTarjeta, importe) == true) {
                JOptionPane.showMessageDialog(this, "Operacion Exitosa");
            } else {
                JOptionPane.showMessageDialog(this, "La Operacion Fracasó");
            }
            
        }
    }//GEN-LAST:event_btnOperarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarTarjeta;
    private javax.swing.JButton btnMostrarReportes;
    private javax.swing.JButton btnOperar;
    private javax.swing.JComboBox<String> cboBoxTipoTarjeta;
    private javax.swing.JComboBox<String> cboBoxTipoTarjetaOperacion;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JLabel lblLimite;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumeroTarjetaOperar;
    private javax.swing.JLabel lblPromedioSaldosTarjetasCredito;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldototalTarjetasDebito;
    private javax.swing.JLabel lblTipoTarjeta;
    private javax.swing.JLabel lblTipoTarjetaOperacion;
    private javax.swing.JLabel lblTitular;
    private javax.swing.JRadioButton rbtDepositar;
    private javax.swing.JRadioButton rbtExtraer;
    private javax.swing.JTextField txtImporteOperar;
    private javax.swing.JTextField txtLimite;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumeroTarjetaOperar;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables
}
